# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_pkg/RockerBogieData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RockerBogieData(genpy.Message):
  _md5sum = "9fabc40ef174095f6a972da72d98b480"
  _type = "rover_pkg/RockerBogieData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 rb_fr
float32 rb_mr
float32 rb_rr
float32 rb_fl
float32 rb_ml
float32 rb_rl

"""
  __slots__ = ['rb_fr','rb_mr','rb_rr','rb_fl','rb_ml','rb_rl']
  _slot_types = ['float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rb_fr,rb_mr,rb_rr,rb_fl,rb_ml,rb_rl

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RockerBogieData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rb_fr is None:
        self.rb_fr = 0.
      if self.rb_mr is None:
        self.rb_mr = 0.
      if self.rb_rr is None:
        self.rb_rr = 0.
      if self.rb_fl is None:
        self.rb_fl = 0.
      if self.rb_ml is None:
        self.rb_ml = 0.
      if self.rb_rl is None:
        self.rb_rl = 0.
    else:
      self.rb_fr = 0.
      self.rb_mr = 0.
      self.rb_rr = 0.
      self.rb_fl = 0.
      self.rb_ml = 0.
      self.rb_rl = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.rb_fr, _x.rb_mr, _x.rb_rr, _x.rb_fl, _x.rb_ml, _x.rb_rl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.rb_fr, _x.rb_mr, _x.rb_rr, _x.rb_fl, _x.rb_ml, _x.rb_rl,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.rb_fr, _x.rb_mr, _x.rb_rr, _x.rb_fl, _x.rb_ml, _x.rb_rl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.rb_fr, _x.rb_mr, _x.rb_rr, _x.rb_fl, _x.rb_ml, _x.rb_rl,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
