// Generated by gencpp from file rover_pkg/ScienceData.msg
// DO NOT EDIT!


#ifndef ROVER_PKG_MESSAGE_SCIENCEDATA_H
#define ROVER_PKG_MESSAGE_SCIENCEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_pkg
{
template <class ContainerAllocator>
struct ScienceData_
{
  typedef ScienceData_<ContainerAllocator> Type;

  ScienceData_()
    {
    }
  ScienceData_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rover_pkg::ScienceData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_pkg::ScienceData_<ContainerAllocator> const> ConstPtr;

}; // struct ScienceData_

typedef ::rover_pkg::ScienceData_<std::allocator<void> > ScienceData;

typedef boost::shared_ptr< ::rover_pkg::ScienceData > ScienceDataPtr;
typedef boost::shared_ptr< ::rover_pkg::ScienceData const> ScienceDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_pkg::ScienceData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_pkg::ScienceData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rover_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rover_pkg::ScienceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_pkg::ScienceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_pkg::ScienceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_pkg::ScienceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_pkg::ScienceData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_pkg::ScienceData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_pkg::ScienceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rover_pkg::ScienceData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_pkg::ScienceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_pkg/ScienceData";
  }

  static const char* value(const ::rover_pkg::ScienceData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_pkg::ScienceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rover_pkg::ScienceData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_pkg::ScienceData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScienceData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_pkg::ScienceData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rover_pkg::ScienceData_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_PKG_MESSAGE_SCIENCEDATA_H
