int32 pressure
int32 rbl_temp
int32 rbr_temp
int32 bmp280_temp

bool st_set
bool st_index

int32 v12_csense
int32 v12_vsense

int32 rb_fr_vel
int32 rb_fr_pos
int32 rb_mr_vel
int32 rb_mr_pos
int32 rb_rr_vel
int32 rb_rr_pos

int32 rb_fl_vel
int32 rb_fl_pos
int32 rb_ml_vel
int32 rb_ml_pos
int32 rb_rl_vel
int32 rb_rl_pos

int32 rb_rb_sig
int32 rb_lb_sig
int32 rb_da_sig

int32 table_sig
int32 bd_sig
int32 ad_sig
int32 wpd_sig
int32 wrd_sig

bool chss_gpio1
bool chss_gpio2
bool chss_gpio3
bool chss_gpio4
bool chss_gpio5
bool chss_gpio6

float32 gx
float32 gy
float32 gz

float32 ax
float32 ay
float32 az

float32 mx
float32 my
float32 mz








