(cl:in-package rover_pkg-msg)
(cl:export '(PRESSURE-VAL
          PRESSURE
          RBL_TEMP-VAL
          RBL_TEMP
          RBR_TEMP-VAL
          RBR_TEMP
          BMP280_TEMP-VAL
          BMP280_TEMP
          ST_SET-VAL
          ST_SET
          ST_INDEX-VAL
          ST_INDEX
          V_CSENSE-VAL
          V_CSENSE
          V_VSENSE-VAL
          V_VSENSE
          RB_FR_VEL-VAL
          RB_FR_VEL
          RB_FR_POS-VAL
          RB_FR_POS
          RB_MR_VEL-VAL
          RB_MR_VEL
          RB_MR_POS-VAL
          RB_MR_POS
          RB_RR_VEL-VAL
          RB_RR_VEL
          RB_RR_POS-VAL
          RB_RR_POS
          RB_FL_VEL-VAL
          RB_FL_VEL
          RB_FL_POS-VAL
          RB_FL_POS
          RB_ML_VEL-VAL
          RB_ML_VEL
          RB_ML_POS-VAL
          RB_ML_POS
          RB_RL_VEL-VAL
          RB_RL_VEL
          RB_RL_POS-VAL
          RB_RL_POS
          RB_RB_SIG-VAL
          RB_RB_SIG
          RB_LB_SIG-VAL
          RB_LB_SIG
          RB_DA_SIG-VAL
          RB_DA_SIG
          TABLE_SIG-VAL
          TABLE_SIG
          BD_SIG-VAL
          BD_SIG
          AD_SIG-VAL
          AD_SIG
          WPD_SIG-VAL
          WPD_SIG
          WRD_SIG-VAL
          WRD_SIG
          CHSS_GPIO1-VAL
          CHSS_GPIO1
          CHSS_GPIO2-VAL
          CHSS_GPIO2
          CHSS_GPIO3-VAL
          CHSS_GPIO3
          CHSS_GPIO4-VAL
          CHSS_GPIO4
          CHSS_GPIO5-VAL
          CHSS_GPIO5
          CHSS_GPIO6-VAL
          CHSS_GPIO6
          GX-VAL
          GX
          GY-VAL
          GY
          GZ-VAL
          GZ
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          MX-VAL
          MX
          MY-VAL
          MY
          MZ-VAL
          MZ
))